image: python:3.7

stages:
  - check
  - package
  - publish

.test-python: &test-python
  before_script:
  - pip install -r requirements.txt
  - pip install .
  script:
  - pytest tests/test_init.py


test-python3.5:
  image: python:3.5
  stage: check
  <<: *test-python

test-python3.6:
  image: python:3.6
  stage: check
  <<: *test-python

test-python3.7:
  image: python:3.7
  stage: check
  <<: *test-python

package:
  stage: package
  variables:
    RELEASE_VERSION: "$CI_JOB_ID"
  before_script:
    - pip install --upgrade pip
    - pip install wheel
  script:
    - python setup.py bdist_wheel --universal
  artifacts:
    paths:
    - dist/*

push_to_repo:
  stage: publish
  dependencies:
  - package
  only:
  - master
  before_script:
  - pip install --upgrade pip
  - pip install twine
  script:
  - >
    TWINE_PASSWORD=${CI_JOB_TOKEN}
    TWINE_USERNAME=gitlab-ci-token
    python -m twine upload
    --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    op_app/dist/* op_auth/dist/* op_event/dist/* op_resource/dist/* op_webapp/dist/*
